apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: hugojesusmr/customer-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8003

---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  ports:
    - targetPort: 8003
      port: 80
  selector:
    app: customer-service