apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-service
  labels:
    app: shopping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-service
  template:
    metadata:
      labels:
        app: shopping-service
    spec:
      containers:
        - name: shopping-service
          image: hugojesusmr/shopping-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8004

---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  ports:
    - targetPort: 8004
      port: 80
  selector:
    app: shopping-service