server:
    port: 8001
  
spring:
  cloud:
    config:
      server: 
        git:
          uri: https://github.com/hugojesusmr/Microservicesk8.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
          default-label: "master"

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

          
   
