apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-deployment
  labels:
    app: spring-boot-k8s
spec:  
 replicas: 2
 selector:
    matchLabels:
        app: spring-boot-k8s
 template:
   metadata:
      labels:
        app: spring-boot-k8s
   spec:
    containers:     
      - name: spring-boot-k8s
        image: hugojesusmr/springboot-k8-example:1.0
        ports:
          - containerPort: 8092
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-svc
spec:         
  type: NodePort   
  ports:
   - port: 8092
     targetPort: 8092
     protocol: TCP  
  selector:
    app: spring-boot-k8s
